[package]
name = "viz"
version = "0.1.0"
authors = ["max jacobsen <maxjacobsendev@gmail.com>"]
edition = "2021"

[dependencies]
nannou = "0.19"
rand = "0.8.5"
itertools = "0.12.1"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
image = "0.25.1"
rayon = "1.10.0"
